apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        env:
        - name: POSTGRES_USER
          value: "postgresadmin"
        - name: POSTGRES_PASSWORD
          value: "admin123"
        - name: POSTGRES_DB
          value: "postgresdb"
        - name: PGPASSWORD
          value: "admin123"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
        - name: "schema"
          mountPath: "/mnt/librarydbschema.sql"
          subPath: "librarydbschema.sql"
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      - name: "schema"
        configMap:
          name: "dbscripts"